### PR TITLE
Home content

### PR DESCRIPTION
**Pull request by asmockler**
Adds content for the home page

screen shot 2019-02-18 at 23 21 56-fullpage

@rickecon we are missing the following content for the home page:

- Double check the content for the left side of the hero section (to the left of the slideshow)
- Content to go over each of the 4 images you sent me via email
- Content and links for the "latest" section

### CODE REVIEW

**Comment by rickecon** [comment]
@asmockler . For the hero section to the left of the slideshow, I would like to use the horizontal logo with the following four bullets below the image. Let me know if you think I should remove the gray bars above and below the horizontal logo image.

ose-horizontal-logo

Open Access and Open Source Computational Economics

* Curriculum
* Research
* Policy
* Collaboration

**Comment by rickecon** [comment]
For the first photo.

evansosminstruction

"It was such a great experience to participate in the [OSE] Bootcamp. After participating in the program, I got a research assistant position simply by just showing the professor my Github and all of the cool Math/Econ/Computation we did in the [OSE] lab."

-Alex Weinberg, University of Chicago

**Comment by rickecon** [comment]
For the second slideshow photo

groupshot2018

The 2018 OSE Lab cohort at the end of the Boot Camp in front of Saieh Hall at the University of Chicago, August 2018.

**Comment by rickecon** [comment]
For the third slideshow photo

hansenlecture2018

Lars Hansen instructs OSE Lab students about macro financial modeling, asset pricing, and model uncertainty (July 11, 2018, Saieh Hall, University of Chicago).

**Comment by rickecon** [comment]
For the fourth photo

groupshot2017

The 2017 OSE Lab cohort at the end of the Boot Camp in front of Saieh Hall at the University of Chicago (August 4, 2017).

**Comment by rickecon** [comment]
I assume that each of these little blurbs will also be a news feed item. For the left-most item under "Latest from OSE Lab" to the right-most:

**Applications open for 2019 OSE Lab Summer Boot Camp**

Applications are now open for the six-week OSE Lab Summer Boot Camp 2019 at the University of Chicago from July 1 to August 9. The boot camp encourages applications from PhD, masters, and advanced undergraduate students in economics. Admitted students receive a $4,000 stipend, and OSE Lab pays for housing and travel to and from Chicago. The deadline to apply is March 15. Click [here](put link) for more information and to submit your application. Also, links to FAQs and student comments.

**2019 OSE Lab Boot Camp teams up with Econometric Society Dynamic Structural Economics Workshop**

We are excited to announce that the 2019 OSE Lab Boot Camp has partnered with the Econometric Society Dynamic Structural Economics Workshop and Conference for our summer boot camps for the next three years. This year, during second week of the OSE Lab Boot Camp, July 8 through July 14, OSE Lab students will join with the other participants in the Dynamic Structural Economics Workshop and the associated two-day conference to learn discrete choice dynamic programming, structural estimation, and dynamic games. 

**Evans presents open source policy model in Washington, DC**

OSE Lab Director, [Richard Evans](https://sites.google.com/site/rickecon/), was a speaker at the Policy Simulation Library Meet-up in Washington, DC at the American Enterprise Institute on January 29, 2019. Evans showed participants how to use the open source [OG-USA model](https://github.com/PSLmodels/OG-USA) for dynamic analysis of federal tax policy changes. Video of the talk is available [here](https://www.youtube.com/watch?time_continue=909&v=jo_PMPipne0) (Evans talk starts at minute 10:29) and slides from the talk are [here](https://sites.google.com/site/rickecon/PSLmeetup.pdf).

**Comment by asmockler** [comment]
Thanks for the content, @rickecon. Here is the home page with those updates:

screen shot 2019-02-19 at 16 35 46-fullpage

The slide content didn't quite follow the pattern I expected when I built those components. I figure we can merge as-is for now and I will do a style cleanup on the slides soon. Sound good?

**Comment by rickecon** [comment]
Yes. The screen shot looks good. I can't quite visualize the problem you are describing with the slideshow, but I will just leave this to you to merge whenever you're ready. Let me know when it is a go.

**Comment by asmockler** [comment]
Just finished deploying to https://www.oselab.org

**Comment by rickecon** [comment]
@asmockler OK. I see the slideshow issue. The pictures are too big, that section of the home page is too tall. How does one fix that? Do we crop the pictures so that a fixed window of each photo shows in the slideshow?

**Comment by asmockler** [comment]
Unfortunately, since the site is responsive, it is basically inevitable that there will be quite a bit of cropping. We can mitigate it by picking pictures where there is quite a bit of space for the image to bleed on the edges (the second image is a great example of this), but for the most part the answer is either to pick images that you don't mind exiting the view port on certain screen sizes or we add some letterboxing around the images, but that will come with its own set of aesthetic problems.

**Pull request merged**
